# Generated by Django 2.0 on 2018-12-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20181220_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-add_time'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
    ]
