# Generated by Django 2.0 on 2018-12-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructions',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='相关课程'),
        ),
    ]
