# Generated by Django 2.0 on 2019-01-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播图课程',
                'verbose_name_plural': '轮播图课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('course.course',),
        ),
    ]
