"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR,'apps'))
sys.path.insert(0, os.path.join(BASE_DIR,'extra_app'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0^0na2!g1pcu2t(vti*c)^35#t*g@rw=y5kedaub13n!$^3bt!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] #防止黑客发送请求,改了DEBUG = False,必须在此['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    #对每次浏览器request进行拦截，找到服务器传过来的sessions的ID，找到此ID就去数据库找到sessions_data(用户信息)
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'xadmin',
    'crispy_forms',
    'users.apps.UsersConfig', #用户重写
    'course.apps.CourseConfig',#课程
    'operation.apps.OperationConfig',#用户操作
    'organization.apps.OrganizationConfig',#课程机构
    'captcha',#注册码
    'pure_pagination', #分页
    'DjangoUeditor', #富文本app
]

#扩展User
AUTH_USER_MODEL = 'users.UserProfile'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media', #上传media图片使得模板显示图片
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
#数据库
DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "testdjango",
        'USER': "root",
        'PASSWORD': "root",
        'HOST': "127.0.0.1",
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'# 上传图片的路径，上传的图片会自动传递给media目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')#文件上传到根目录media中

#DEBUG = flase会使得django失效自动识别static。手动加载static
# STATIC_ROOT = os.path.join(BASE_DIR, '/static/')


#重写authentication#记得加逗号，不然会出现奇怪的bug
AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)

#发送邮箱
EMAIL_HOST = "smtp.qq.com"  # SMTP服务器主机
EMAIL_PORT = 25             # 端口
EMAIL_HOST_USER = "1272443075@qq.com"       # 邮箱地址
EMAIL_HOST_PASSWORD = "irfdbbeesjgeiaac"    # 密码
EMAIL_USE_TLS = True
EMAIL_FROM = "1272443075@qq.com"            # 邮箱地址要和EMAIL_HOST_USER保持一致

#分页
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 10, #分页中间的页码
    'MARGIN_PAGES_DISPLAYED': 2, #中间左右两边的页码范围两个
    'SHOW_FIRST_PAGE_WHEN_INVALID': True, #使用...
}

