# Generated by Django 2.0 on 2018-12-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'ordering': ['-add_time'], 'verbose_name': '用户评论', 'verbose_name_plural': '用户评论'},
        ),
    ]
