# Generated by Django 2.0 on 2019-01-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190125_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址'),
        ),
    ]
