# Generated by Django 2.0 on 2019-01-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190125_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, default='banner/default.png', null=True, upload_to='banner/%Y%m', verbose_name='轮播图'),
        ),
    ]
