# Generated by Django 2.0 on 2018-12-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20181220_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='teacher/default_middile_1.png', null=True, upload_to='teacher/%Y%m', verbose_name='老师头像'),
        ),
    ]
