# Generated by Django 2.0 on 2019-01-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20181224_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=25, verbose_name='教师年龄'),
        ),
    ]
