# Generated by Django 2.0 on 2019-01-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(blank=True, default='全国知名', max_length=15, null=True, verbose_name='标签'),
        ),
    ]
